load("@prelude//go:go_binary.bzl", "go_tool_binary")
prelude = native

prelude.python_bootstrap_binary(
    name = "compile_wrapper",
    main = "compile_wrapper.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "cover_srcs",
    main = "cover_srcs.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "filter_srcs",
    main = "filter_srcs.py",
    visibility = ["PUBLIC"],
)

prelude.python_bootstrap_binary(
    name = "cgo_wrapper",
    main = "cgo_wrapper.py",
    visibility = ["PUBLIC"],
)

prelude.go_binary(
    name = "testmaingen",
    srcs = [
        "testmaingen.go",
    ],
    visibility = [
        "PUBLIC",
    ],
)

go_tool_binary(
    name = "testmaingen2",
    srcs = ["testmaingen.go"],
    visibility = ["PUBLIC"],
)
