/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is dual-licensed under either the MIT license found in the
 * LICENSE-MIT file in the root directory of this source tree or the Apache
 * License, Version 2.0 found in the LICENSE-APACHE file in the root directory
 * of this source tree. You may select, at your option, one of the
 * above-listed licenses.
 */

package gobuckifylib

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEscapeModulePath(t *testing.T) {
	got := escapeModulePath("github.com/Azure/azure-sdk-for-go")
	want := "github.com/!azure/azure-sdk-for-go"
	if got != want {
		t.Fatalf("escapeModulePath() = %q, want %q", got, want)
	}
}

func TestRenderGoModBuck(t *testing.T) {
	out := renderGoModBuck(
		[]*goModArchive{{
			Name:        "gomod_github.com_example_dep_v1.2.3",
			Out:         "gomod_github.com_example_dep_v1.2.3",
			URL:         "https://proxy.golang.org/github.com/example/dep/@v/v1.2.3.zip",
			SHA256:      "0123456789abcdef",
			StripPrefix: "github.com/example/dep@v1.2.3",
			SubTargets:  []string{"subpkg/dep.go"},
			Patches:     []string{"//buildpatches:dep.patch"},
			PatchArgs:   []string{"-p1"},
		}},
		[]*goModTarget{{
			Name:        "subpkg",
			Rule:        "go_library",
			ImportPath:  "github.com/example/dep/subpkg",
			PackageRoot: "gomod_github.com_example_dep_v1.2.3/subpkg",
			Srcs:        []string{":gomod_github.com_example_dep_v1.2.3[subpkg/dep.go]"},
			Deps:        []string{"//third_party/go:other"},
		}},
		nil,
	)

	for _, want := range []string{
		"# @generated by gobuckify gomod; do not edit.",
		"http_archive(",
		"strip_prefix = \"github.com/example/dep@v1.2.3\"",
		"sha256 = \"0123456789abcdef\"",
		"patches = [",
		"//buildpatches:dep.patch",
		"patch_args = [",
		"sub_targets = [",
		"go_library(",
		"import_path = \"github.com/example/dep/subpkg\"",
		"package_root = \"gomod_github.com_example_dep_v1.2.3/subpkg\"",
		"//third_party/go:other",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("rendered BUCK missing %q:\n%s", want, out)
		}
	}
}

func TestRenderGoModBuckProtoCompilers(t *testing.T) {
	out := renderGoModBuck(
		nil,
		nil,
		[]*goModProtoTarget{{
			Name:       "service_go_proto",
			Dir:        "proto",
			ImportPath: "github.com/example/project/proto",
			Srcs:       []string{"proto/service.proto"},
			ImportMappings: map[string]string{
				"google/api/annotations.proto": "google.golang.org/genproto/googleapis/api/annotations",
			},
			Deps:        []string{"//third_party/go:google.golang.org/genproto/googleapis/api/annotations"},
			GRPC:        true,
			GRPCSrcs:    []string{"proto/service.proto"},
			VTProto:     true,
			VTProtoSrcs: []string{"proto/service.proto"},
		}},
	)

	for _, want := range []string{
		"load(\"@prelude//go:go_proto_library.bzl\", \"go_proto_compiler\", \"go_proto_library\")",
		"go_proto_compiler(",
		"name = \"go_proto\"",
		"plugin_name = \"go\"",
		"plugin = \"//third_party/go:protoc-gen-go\"",
		"name = \"go_grpc_v2\"",
		"plugin_name = \"go-grpc\"",
		"suffix = \"_grpc.pb.go\"",
		"require_unimplemented_servers=false",
		"name = \"go_vtproto\"",
		"plugin_name = \"go-vtproto\"",
		"features=marshal+unmarshal+size+pool+clone",
		"go_proto_library(",
		"import_path = \"github.com/example/project/proto\"",
		"compilers = [",
		"\":go_proto\"",
		"\":go_grpc_v2\"",
		"\":go_vtproto\"",
		"grpc_src_paths = [",
		"vtproto_src_paths = [",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("rendered proto BUCK missing %q:\n%s", want, out)
		}
	}
}

func TestQueryGoModulePatches(t *testing.T) {
	dir := t.TempDir()
	moduleContent := "module(\n" +
		"    name = \"buildbuddy\",\n" +
		"    repo_name = \"com_github_buildbuddy_io_buildbuddy\",\n" +
		")\n\n" +
		"include(\"//deps:go_deps.MODULE.bazel\")\n"
	if err := os.WriteFile(filepath.Join(dir, "MODULE.bazel"), []byte(moduleContent), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "deps"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "buildpatches"), 0755); err != nil {
		t.Fatal(err)
	}
	depsContent := "go_deps.module_override(\n" +
		"    patch_strip = 1,\n" +
		"    patches = [\n" +
		"        \"@com_github_buildbuddy_io_buildbuddy//buildpatches:local.patch\",\n" +
		"        \"@com_github_buildbuddy_io_buildbuddy//buildpatches:metadata.patch\",\n" +
		"        \"@io_bazel_rules_go//third_party:ignored.patch\",\n" +
		"    ],\n" +
		"    # Comments may contain calls like panic().\n" +
		"    path = \"github.com/example/dep\",\n" +
		")\n"
	if err := os.WriteFile(filepath.Join(dir, "deps", "go_deps.MODULE.bazel"), []byte(depsContent), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "buildpatches", "local.patch"), []byte("diff --git a/foo.go b/foo.go\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "buildpatches", "metadata.patch"), []byte("diff --git a/BUILD.bazel b/BUILD.bazel\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if ok, err := isGoSourcePatch(dir, "//buildpatches:local.patch"); err != nil || !ok {
		t.Fatalf("local patch source check = %v, %v", ok, err)
	}
	if ok, err := isGoSourcePatch(dir, "//buildpatches:metadata.patch"); err != nil || ok {
		t.Fatalf("metadata patch source check = %v, %v", ok, err)
	}
	patches, err := queryGoModulePatches(dir, "github.com/buildbuddy-io/buildbuddy")
	if err != nil {
		t.Fatal(err)
	}
	got := patches["github.com/example/dep"]
	if len(got.Patches) != 1 || got.Patches[0] != "//buildpatches:local.patch" {
		t.Fatalf("patches = %#v", got.Patches)
	}
	if len(got.PatchArgs) != 1 || got.PatchArgs[0] != "-p1" {
		t.Fatalf("patch args = %#v", got.PatchArgs)
	}
}

func TestArchiveForPackageEscapesURLOnly(t *testing.T) {
	modDir := filepath.Join(string(filepath.Separator), "gomod", "github.com", "Masterminds", "semver", "v3@v3.4.0")
	pkgDir := filepath.Join(modDir, "constraints")
	state := &goModState{
		RootModule:  &Module{Path: "example.com/root"},
		Archives:    map[string]*goModArchive{},
		FilesByDir:  map[string][]string{"github.com/Masterminds/semver/v3/constraints": {"constraints.go"}},
		ZipSHA256:   map[string]string{"github.com/Masterminds/semver/v3@v3.4.0": "abcd"},
		TargetNames: map[string]string{},
	}

	archive, pkgRel, err := state.archiveForPackage(&GoModPackage{
		Dir:        pkgDir,
		ImportPath: "github.com/Masterminds/semver/v3/constraints",
		Module: &Module{
			Path:    "github.com/Masterminds/semver/v3",
			Version: "v3.4.0",
			Dir:     modDir,
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if pkgRel != "constraints" {
		t.Fatalf("pkgRel = %q, want constraints", pkgRel)
	}
	if archive.URL != "https://proxy.golang.org/github.com/!masterminds/semver/v3/@v/v3.4.0.zip" {
		t.Fatalf("URL = %q", archive.URL)
	}
	if archive.StripPrefix != "github.com/Masterminds/semver/v3@v3.4.0" {
		t.Fatalf("StripPrefix = %q", archive.StripPrefix)
	}
}

func TestSelectRootModuleFromGoWorkModules(t *testing.T) {
	dir := t.TempDir()
	rootDir := filepath.Join(dir, "root")
	depDir := filepath.Join(dir, "dep")
	out := []byte(moduleJSON(t, &Module{
		Path:  "example.com/dep",
		Dir:   depDir,
		GoMod: filepath.Join(depDir, "go.mod"),
		Main:  true,
	}) + "\n" + moduleJSON(t, &Module{
		Path:  "example.com/root",
		Dir:   rootDir,
		GoMod: filepath.Join(rootDir, "go.mod"),
		Main:  true,
	}) + "\n")

	mod, err := selectRootModule(out, rootDir, filepath.Join(rootDir, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	if mod.Path != "example.com/root" || mod.Dir != rootDir {
		t.Fatalf("selected module = %#v", mod)
	}
}

func TestLocalReplacePackagesAreGeneratedLocally(t *testing.T) {
	dir := t.TempDir()
	appDir := filepath.Join(dir, "app")
	localModuleDir := filepath.Join(dir, "localdep")
	localPkgDir := filepath.Join(localModuleDir, "pkg")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(localPkgDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(appDir, "main.go"), []byte("package main\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(localPkgDir, "pkg.go"), []byte("package pkg\n"), 0644); err != nil {
		t.Fatal(err)
	}

	rootPkg := &GoModPackage{
		Dir:        appDir,
		ImportPath: "example.com/root/app",
		Name:       "main",
		Module: &Module{
			Path: "example.com/root",
			Dir:  dir,
		},
		Imports: []string{"example.com/localdep/pkg"},
		GoFiles: []string{"main.go"},
	}
	localPkg := &GoModPackage{
		Dir:        localPkgDir,
		ImportPath: "example.com/localdep/pkg",
		Name:       "pkg",
		Module: &Module{
			Path:    "example.com/localdep",
			Version: "v0.0.0",
			Dir:     localModuleDir,
			Replace: &Module{
				Path: "./localdep",
				Dir:  localModuleDir,
			},
		},
		GoFiles: []string{"pkg.go"},
	}
	state := &goModState{
		RootDir:       dir,
		RootModule:    &Module{Path: "example.com/root", Dir: dir},
		Packages:      map[string]*GoModPackage{},
		Labels:        map[string]string{},
		TargetNames:   map[string]string{},
		Archives:      map[string]*goModArchive{},
		ProtoArchives: map[string]*goModArchive{},
		ModulePatches: map[string]goModModulePatch{},
		FilesByDir:    map[string][]string{},
		ZipSHA256:     map[string]string{},
	}
	for _, pkg := range []*GoModPackage{rootPkg, localPkg} {
		state.Packages[pkg.ImportPath] = pkg
		state.FilesByDir[pkg.ImportPath] = packageFiles(pkg)
		state.Labels[pkg.ImportPath] = state.labelForPackage(pkg)
	}
	if got := state.Labels["example.com/localdep/pkg"]; got != "//localdep/pkg:pkg" {
		t.Fatalf("local replacement label = %q", got)
	}
	checksums, err := queryModuleZipSHA256(dir, []*GoModPackage{localPkg})
	if err != nil {
		t.Fatal(err)
	}
	if len(checksums) != 0 {
		t.Fatalf("local replacement checksums = %#v", checksums)
	}
	if err := state.writeRootPackageFiles(); err != nil {
		t.Fatal(err)
	}
	if err := state.writeThirdPartyFile(); err != nil {
		t.Fatal(err)
	}

	appBuck := readFile(t, filepath.Join(appDir, GoModBuckFileName))
	for _, want := range []string{
		"import_path = \"example.com/root/app\"",
		"\"//localdep/pkg:pkg\"",
	} {
		if !strings.Contains(appBuck, want) {
			t.Fatalf("root BUCK missing %q:\n%s", want, appBuck)
		}
	}
	localBuck := readFile(t, filepath.Join(localPkgDir, GoModBuckFileName))
	for _, want := range []string{
		"go_library(",
		"import_path = \"example.com/localdep/pkg\"",
		"\"pkg.go\"",
	} {
		if !strings.Contains(localBuck, want) {
			t.Fatalf("local replacement BUCK missing %q:\n%s", want, localBuck)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "third_party", "go", GoModBuckFileName)); !os.IsNotExist(err) {
		t.Fatalf("third-party BUCK exists for local-only packages: %v", err)
	}
}

func TestGenerateGoModBuckFilesLocalReplace(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "localdep"), 0755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, filepath.Join(dir, "go.mod"), "module example.com/root\n\ngo 1.22\n\nrequire example.com/dep v0.0.0\n\nreplace example.com/dep => ./localdep\n")
	writeFile(t, filepath.Join(dir, "main.go"), "package main\n\nimport \"example.com/dep\"\n\nfunc main() { _ = dep.Value() }\n")
	writeFile(t, filepath.Join(dir, "localdep", "go.mod"), "module example.com/dep\n\ngo 1.22\n")
	writeFile(t, filepath.Join(dir, "localdep", "dep.go"), "package dep\n\nfunc Value() string { return \"local\" }\n")

	if err := GenerateGoModBuckFiles(dir, []string{"./..."}); err != nil {
		t.Fatal(err)
	}
	rootBuck := readFile(t, filepath.Join(dir, GoModBuckFileName))
	for _, want := range []string{
		"import_path = \"example.com/root\"",
		"\"//localdep:dep\"",
	} {
		if !strings.Contains(rootBuck, want) {
			t.Fatalf("root BUCK missing %q:\n%s", want, rootBuck)
		}
	}
	localBuck := readFile(t, filepath.Join(dir, "localdep", GoModBuckFileName))
	for _, want := range []string{
		"go_library(",
		"import_path = \"example.com/dep\"",
		"\"dep.go\"",
	} {
		if !strings.Contains(localBuck, want) {
			t.Fatalf("local BUCK missing %q:\n%s", want, localBuck)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "third_party", "go", GoModBuckFileName)); !os.IsNotExist(err) {
		t.Fatalf("third-party BUCK exists for local-only packages: %v", err)
	}
}

func moduleJSON(t *testing.T, mod *Module) string {
	t.Helper()
	out, err := json.Marshal(mod)
	if err != nil {
		t.Fatal(err)
	}
	return string(out)
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(content)
}

func writeFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}
