load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")

oncall("build_infra")

system_cxx_toolchain(
    name = "cxx",
    archiver = "/usr/bin/ar",
    compiler = "/usr/bin/gcc",
    compiler_type = "gcc",
    cxx_compiler = "/usr/bin/g++",
    linker = "g++",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    interpreter = "python3",
    visibility = ["PUBLIC"],
)
